logistica:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-analytics
      user: analytics
      password: analytics
      port: 5432
      dbname: analytics
      schema: public
      threads: 4
